### ISSUE TITLE
2 audio device on same page

### ISSUE THREAD

**Issue by BBjen819** [KillerBOSS2019/TouchPortal-Windows-MediaMixer#1]
1st. Love your software.

Bug: When trying to set output and input on the same page, while selecting the second as input, both lines of the page changes back.
My work around was to create a flow for one of them.

**Comment by DamienStaebler** [comment]
Thanks for using the software. Can I ask for a photo or a video of this so I have a clear understanding of it please.

**Comment by BBjen819** [comment]
Hrer you go.
[https://www.youtube.com/watch?v=L_1jc8d_s7A&feature=youtu.be](url)

**Comment by DamienStaebler** [comment]
ahhh... I see the problem... because there isn't a way to update specific instance of action. so when I update a list it updates to all of them. the workaround is copy the action after you selected those field and paste the copied action once you finish the 2nd action. if that makes any sense. Sorry for very late response I completely forgot about this.

**Comment by KillerBOSS2019** [comment]
Ok sorry for that I

**Comment by DamienStaebler** [comment]
Sorry. my mistake I thought there wasn't a way to specific instances. anyways Latest Version 1.3.1 should solve that. Let me know how it turned out!
